set -u
case "${DRIVERS:-}" in
  success) drv="화면 검사 드라이버는 **전부 통과했습니다.** 빨간 단계는 그 밖(앞의 값싼 관문 · 말투·토큰 · 수집기 규칙 · 전 여정 등)에 있으니, 로그에서 빨간 표시가 붙은 단계를 찾으세요." ;;
  failure)
    if [ -n "${FAILED:-}" ]; then
      drv="실패한 드라이버: ${FAILED}. 드라이버는 하나가 넘어져도 끝까지 돌았습니다. 다른 빨간 단계가 더 있을 수 있으니 로그도 보세요."
    else
      drv="화면 검사 단계가 실패했는데 실패한 드라이버 목록을 받지 못했습니다 — 로그에서 \`❌\` 가 붙은 줄과 빨간 단계를 찾으세요."
    fi ;;
  *) drv="화면 검사 드라이버와 전 여정(drive.js)이 **돌지 않았습니다** — 그 앞의 준비 단계(코드 내려받기 · 도구 설치 · 브라우저 설치 · 로컬 서버 띄우기) 가운데 하나가 실패했습니다. 로그에서 빨간 표시가 붙은 단계를 찾으세요." ;;
esac
body="**앱 화면 검사(브라우저)가 빨간불입니다.** 화면이나 판정이 깨졌다는 뜻입니다.

· 브랜치: \`${BRANCH}\`
· 시각: $(TZ=Asia/Seoul date '+%Y-%m-%d %H:%M') KST
· 실행 로그: ${RUN_URL}

${drv}

다음 Claude 세션에 \"화면 검사 빨간불 고쳐줘\" 라고 지시하세요.

---
_Generated by [Claude Code](https://claude.ai/code)_"
gh label create ui-gate --repo "$REPO" --color B60205 \
  --description "앱 화면 검사(verify-ui)가 빨간불" 2>/dev/null || true
n=$(gh issue list --repo "$REPO" --label ui-gate --state open \
      --limit 1 --json number --jq '.[0].number' 2>/dev/null || true)
if [ -n "$n" ] && [ "$n" != "null" ]; then
  gh issue comment "$n" --repo "$REPO" --body "$body"
else
  gh issue create --repo "$REPO" --label ui-gate \
    --title "🚨 앱 화면 검사가 빨간불입니다 ($(TZ=Asia/Seoul date '+%Y-%m-%d %H:%M') KST)" \
    --body "$body"
fi
